name: my_first_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  pdf: ^3.10.7
  printing: ^5.11.1
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  http: ^1.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/header_banner.png
